### ISSUE TITLE
Oddity in pqrs code

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/sotgrps#38]
The code in `pqrs.gi` has many lines of the form
```gap
        Add(all, [ [p, q, r, s], ..... ]);
```

But in line 178 (and again in its "twin" in line 371), it says: `[p, r, q, s]`

Now, I am guessing this is intentional, and explained somewhere in your thesis or in your paper; but it at least is surprising when seeing it. So I think it would be helpful to at least add a comment stating that it is intentional, and providing a citation pointing at an explanation.

(Of course if this is *not* intentional it should also be resolved ;-) )

**Comment by xpan-eileen** [comment]
There was actually no important reason why they had to be in that order. Just changed them into the usual order `[p, q, r, s]` now.
